export const projects = [
  {
    id: 1,
    title: "Solar-Powered EV Charging Station",
    description: "Designed and implemented an off-grid EV charging solution using solar panels, MPPT controllers, and battery management systems. Integrated real-time monitoring via IoT sensors for power optimization.",
    problem: "Limited EV charging infrastructure in remote areas with unreliable grid power",
    solution: "Autonomous solar charging station with intelligent load balancing and remote monitoring",
    tags: ["Solar Energy", "EV Charging", "IoT", "Power Electronics", "Battery Management"],
    image: "/projects/solar-ev.jpg",
    github: "https://github.com/yourusername/solar-ev-charging",
    hackster: "https://www.hackster.io/yourusername/solar-ev-charging",
    demo: null,
  },
  {
    id: 2,
    title: "Li-Fi Based Vehicle Communication System",
    description: "Developed a visible light communication system for vehicle-to-vehicle (V2V) data transmission using LED headlights and photodetectors. Achieved 10 Mbps data rates for safety-critical messaging.",
    problem: "RF-based V2V systems face interference and security vulnerabilities",
    solution: "Line-of-sight Li-Fi system with modulated LED signals for secure, high-speed communication",
    tags: ["Li-Fi", "Optical Communication", "Embedded C", "Signal Processing", "Automotive"],
    image: "/projects/lifi-vehicle.jpg",
    github: "https://github.com/yourusername/lifi-vehicle-comm",
    hackster: "https://www.hackster.io/yourusername/lifi-vehicle-communication",
    demo: null,
  },
  {
    id: 3,
    title: "GSM + Raspberry Pi DIY Vehicle Tracker",
    description: "Built a real-time vehicle tracking and diagnostics system using Raspberry Pi, GSM module, and OBD-II interface. Features geofencing alerts, fuel monitoring, and remote engine diagnostics.",
    problem: "Commercial vehicle tracking systems are expensive and lack customization",
    solution: "Open-source tracker with custom firmware, web dashboard, and SMS alerts",
    tags: ["Raspberry Pi", "GSM", "GPS", "Python", "OBD-II", "Web Dashboard"],
    image: "/projects/vehicle-tracker.jpg",
    github: "https://github.com/yourusername/vehicle-tracker",
    hackster: "https://www.hackster.io/yourusername/gsm-vehicle-tracker",
    demo: null,
  },
  {
    id: 4,
    title: "Smart Home Automation with ESP32",
    description: "Designed a modular home automation system using ESP32 microcontrollers, MQTT protocol, and custom PCBs. Integrated temperature, humidity, motion, and light sensors with mobile app control.",
    problem: "Existing smart home solutions are proprietary and cloud-dependent",
    solution: "Local-first automation system with optional cloud sync and voice control integration",
    tags: ["ESP32", "MQTT", "Home Automation", "PCB Design", "Mobile App", "Sensors"],
    image: "/projects/smart-home.jpg",
    github: "https://github.com/yourusername/esp32-smart-home",
    hackster: null,
    demo: null,
  },
  {
    id: 5,
    title: "Industrial Sensor Network for Predictive Maintenance",
    description: "Deployed a wireless sensor network in manufacturing facility to monitor vibration, temperature, and acoustic signatures of machinery. ML algorithms predict equipment failures 48 hours in advance.",
    problem: "Unplanned equipment downtime costs manufacturers millions annually",
    solution: "LoRaWAN sensor mesh with edge computing for real-time anomaly detection",
    tags: ["LoRaWAN", "Predictive Maintenance", "Machine Learning", "Industrial IoT", "Edge Computing"],
    image: "/projects/predictive-maintenance.jpg",
    github: null,
    hackster: null,
    demo: null,
  },
  {
    id: 6,
    title: "Precision Agriculture Monitoring System",
    description: "Created a solar-powered field monitoring system with soil moisture, pH, NPK, and weather sensors. Data transmitted via LoRa to cloud platform for irrigation optimization and crop health analysis.",
    problem: "Farmers lack real-time data for precision irrigation and fertilization decisions",
    solution: "Low-power sensor nodes with 6-month battery life and automated irrigation triggers",
    tags: ["Agriculture", "LoRa", "Solar Power", "Soil Sensors", "Cloud Platform", "Data Analytics"],
    image: "/projects/agri-monitoring.jpg",
    github: "https://github.com/yourusername/agri-monitoring",
    hackster: "https://www.hackster.io/yourusername/precision-agriculture",
    demo: null,
  },
];

export const skills = {
  "Embedded Systems": [
    "ARM Cortex-M",
    "ESP32/ESP8266",
    "Raspberry Pi",
    "Arduino",
    "STM32",
    "PIC Microcontrollers",
    "RTOS (FreeRTOS)",
    "Embedded C/C++",
  ],
  "Sensors & Instrumentation": [
    "Temperature & Humidity",
    "Pressure & Flow",
    "Accelerometer & Gyroscope",
    "Gas & Air Quality",
    "Optical Sensors",
    "Load Cells",
    "Current & Voltage Sensing",
    "Signal Conditioning",
  ],
  "Communication Protocols": [
    "UART/SPI/I2C",
    "CAN Bus",
    "Modbus RTU/TCP",
    "MQTT",
    "LoRaWAN",
    "Zigbee",
    "BLE",
    "Wi-Fi",
  ],
  "Power & Solar": [
    "Solar Panel Design",
    "MPPT Controllers",
    "Battery Management Systems",
    "DC-DC Converters",
    "Power Electronics",
    "Energy Harvesting",
    "Grid-Tie Inverters",
  ],
  "Software & Tools": [
    "Python",
    "C/C++",
    "MATLAB/Simulink",
    "KiCad/Altium",
    "Git",
    "Docker",
    "Node.js",
    "React",
  ],
  "Design & Prototyping": [
    "PCB Design",
    "Schematic Capture",
    "3D Printing",
    "Soldering & Assembly",
    "Oscilloscope",
    "Logic Analyzer",
    "Multimeter",
    "Function Generator",
  ],
};

export const experience = [
  {
    title: "Founder & Lead Engineer",
    company: "Sensoreact",
    period: "2023 - Present",
    description: "Building next-generation sensor solutions and IoT platforms for industrial and consumer applications.",
    achievements: [
      "Developed proprietary sensor fusion algorithms",
      "Designed custom PCBs for production deployment",
      "Established partnerships with manufacturing clients",
    ],
  },
  {
    title: "Embedded Systems Engineer",
    company: "Previous Company / Freelance",
    period: "2021 - 2023",
    description: "Designed and deployed embedded solutions for automotive, industrial, and renewable energy sectors.",
    achievements: [
      "Led development of vehicle telematics platform",
      "Reduced power consumption by 40% through optimization",
      "Mentored junior engineers in embedded best practices",
    ],
  },
];
